services:
  ipfs:
    build: 
      context: ./ipfs
    restart: unless-stopped
    entrypoint: [ "/bin/sh", "/scripts/init.private.sh" ]
    env_file:
      - ../.env
    volumes:
      - ./ipfs/:/scripts
      - ipfs_fuse:/ipfs
      - ipns_fuse:/ipns
    ports:
      - "4001:4001/tcp"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
  nginx:
    image: nginx
    restart: unless-stopped
    # ports:
    #   - "8080:80"
    #   - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    network_mode: host
    depends_on:
      - ipfs

# persisting named volumes
volumes:
  ipfs_fuse:
  ipns_fuse: